### ISSUE TITLE
Always showing

### ISSUE THREAD

**Issue by Milky063** [The-Sickness/CursorGlow#1]
Is there a way to make a ring always show instead of shrinking and disappearing? Would be a great if you could add this so the ring is always showing. Thank you

**Comment by The-Sickness** [comment]
Yes, I can do that. Give me a little bit of time and I can make it happen.

**Comment by Milky063** [comment]
Thank you! looking forward to that. I just need it up all the time because as a healer, knowing where the cursor is for my healing frames is huge. ❤️
________________________________

**Comment by The-Sickness** [comment]
It's done.
