### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by EKE00372** [The-Sickness/CursorGlow#2]
I saw Localization page on curse is enable, but no entry for translate, also check addon code it didnt support localzation. Do you have plan for that? I can support zhTW/zhCN.

**Comment by The-Sickness** [comment]
I can add it in. I completely forgot about that.

**Comment by The-Sickness** [comment]
It is now added and has been uploaded.

**Comment by EKE00372** [comment]
Should I directly translate with GitHub PR? can do it right now

**Comment by The-Sickness** [comment]
I know you can do a PR. But I think you upload it on my Curse page....Do it on Curse. That way it goes directly into my code. If we do A PR I'll have to do an update on Curse.

**Comment by The-Sickness** [comment]
I merged the fork, and I also added them on Curse. I also added you as a contributor.....
